version: '2'  # version of compose format 

services:
  observatory-service:
    build: ./observatory  # path is relative to docker-compose.yml localtion
    volumes:
      - ./website:/var/www/html
      
    ports:
      - 5001:80  # host:container

  website:
    image: php:apache  # pulling image from DockerHub
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80  # host:container
    depends_on:
      - observatory-service  # website is not going to work 
                             # unless observatory-service is running
  zabbix:
    restart: unless-stopped
    container_name: zabbix
    image: zabbix/zabbix-appliance:ubuntu-3.4-latest
    ports: 
      - 5002:80
  
# // reference https://github.com/Einsteinish/docker-compose-flask-rest-api-service-container-and-apache-container.git
